### PR TITLE
Switches favicon for a nice and soulful one

### PR DESCRIPTION
**Pull request by its-unironically-over**
This is a favicon created in the ancient local install times for a project. Let's use it! It's pretty, it has thread history, and the black and white favicon gets mixed in with a lot of stuff I usually have open. A lot of favicons are black and white.

android-chrome-192x192

### CODE REVIEW

**Comment by cr4bl1fe** [comment]
Can you change the bottom text ("dungeon") to "prompts"? and add a favicon.ico (48x48)

**Comment by its-unironically-over** [comment]
Sure thing

**Comment by its-unironically-over** [comment]
Let me know if you want any more changes, I played around a decent bit with the font and this turned out to be the best option

android-chrome-192x192

**Comment by cr4bl1fe** [comment]
deployed

**Pull request merged**
